##########################################################
# Sample .aider.conf.yml
# This file lists *all* the valid configuration entries.
# Place in your home dir, or at the root of your git repo.
##########################################################

# Note: You can only put OpenAI and Anthropic API keys in the YAML
# config file. Keys for all APIs can be stored in a .env file
# https://aider.chat/docs/config/dotenv.html

##########
# options:

## show this help message and exit
#help: xxx

#############
# Main model:

## Specify the model to use for the main chat
model: work-sonnet4

########################
# API Keys and settings:

#################
# Model settings:

## Add a model alias (can be used multiple times)
alias:
  - work-sonnet4:bedrock/arn:aws:bedrock:us-east-1:274460373520:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0
  - work-sonnet3.7:bedrock/arn:aws:bedrock:us-east-1:274460373520:inference-profile/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  - work-opus4:bedrock/arn:aws:bedrock:us-east-1:274460373520:inference-profile/us.anthropic.claude-opus-4-20250514-v1:0

## Set the reasoning_effort API parameter (default: not set)
#reasoning-effort: xxx

## Set the thinking token budget for models that support it. Use 0 to disable. (default: not set)
thinking-tokens: 16k

## Verify the SSL cert when connecting to models (default: True)
#verify-ssl: true

## Timeout in seconds for API calls (default: None)
timeout: "15"

## Specify what edit format the LLM should use (default depends on model)
#edit-format: xxx

#################
# Cache settings:

## Enable caching of prompts (default: False)
cache-prompts: true

## Show diffs when committing changes (default: False)
show-diffs: true
# show-model-warnings: false

###############
# Git settings:

## Enable/disable looking for a git repo (default: True)
#git: true

## Enable/disable adding .aider* to .gitignore (default: True)
#gitignore: true

## Enable/disable the addition of files listed in .gitignore to Aider's editing scope.
#add-gitignore-files: false

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false
## Enable/disable commits when repo is found dirty (default: True)
dirty-commits: false
## Attribute aider code changes in the git author name (default: True). If explicitly set to True, overrides --attribute-co-authored-by precedence.
#attribute-author: xxx

## Attribute aider commits in the git committer name (default: True). If explicitly set to True, overrides --attribute-co-authored-by precedence for aider edits.
#attribute-committer: xxx

## Prefix commit messages with 'aider: ' if aider authored the changes (default: False)
#attribute-commit-message-author: false

## Prefix all commit messages with 'aider: ' (default: False)
#attribute-commit-message-committer: false

## Attribute aider edits using the Co-authored-by trailer in the commit message (default: True). If True, this takes precedence over default --attribute-author and --attribute-committer behavior unless they are explicitly set to True.
attribute-co-authored-by: false
## Enable/disable git pre-commit hooks with --no-verify (default: False)
#git-commit-verify: false

## Commit all pending changes with a suitable commit message, then exit
#commit: false

## Specify a custom prompt for generating commit messages
#commit-prompt: xxx

## Perform a dry run without modifying files (default: False)
#dry-run: false

## Skip the sanity check for the git repository (default: False)
#skip-sanity-check-repo: false

## Enable/disable watching files for ai coding comments (default: False)
#watch-files: false

########################
# Fixing and committing:

## Lint and fix provided files, or dirty files if none provided
#lint: false

## Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)
#lint-cmd: xxx
## Specify multiple values like this:
#lint-cmd:
#  - xxx
#  - yyy
#  - zzz

## Enable/disable automatic linting after changes (default: True)
#auto-lint: true

## Specify command to run tests
#test-cmd: xxx

## Enable/disable automatic testing after changes (default: False)
#auto-test: false

## Run tests, fix problems found and then exit
#test: false

############
# Analytics:

## Enable/disable analytics for current session (default: random)
#analytics: xxx

## Specify a file to log analytics events
#analytics-log: xxx

## Permanently disable analytics
#analytics-disable: false

## Send analytics to custom PostHog instance
#analytics-posthog-host: xxx

## Send analytics to custom PostHog project
#analytics-posthog-project-api-key: xxx

############
# Upgrading:

## Check for new aider versions on launch
#check-update: true

## Show release notes on first run of new version (default: None, ask user)
#show-release-notes: xxx

#################
# Other settings:

## Never prompt for or attempt to install Playwright for web scraping (default: False).
#disable-playwright: false

## Use VI editing mode in the terminal (default: False)
vim: true
