#!/bin/zsh
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# Updated bar config for floating appearance
sketchybar --bar position=top height=30 blur_radius=30 color=0x40000000 \
               margin=10 corner_radius=15 border_width=1 border_color=0x20ffffff \
               y_offset=5

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  blur_radius=30
  popup.y_offset=5
  popup.blur_radius=30
  popup.background.corner_radius=5
  popup.background.color=0x40000000
  popup.background.border_width=1
  popup.background.border_color=0x20ffffff
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# Add the event
sketchybar --add event aerospace_workspace_change

# Add a single item for the current workspace
sketchybar --add item aerospace left \
    --subscribe aerospace aerospace_workspace_change \
    --set aerospace \
    background.color=0x44ffffff \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=on \
    label.padding_left=0 \
    label.padding_right=8 \
    label="$(aerospace list-workspaces --focused)" \
    click_script="echo 'Current workspace clicked'" \
    script="$CONFIG_DIR/plugins/aerospace_workspace.sh"

# Modify aerospace item to add popup menu
sketchybar --set aerospace click_script="$PLUGIN_DIR/aerospace_menu.sh" \
                          popup.drawing=on \
                          popup.align=left \
                          popup.height=25 \

# Add popup items for aerospace menu
sketchybar --add item aerospace.reload popup.aerospace \
           --set aerospace.reload icon="↻" \
                                 label="Reload Config" \
                                 click_script="$PLUGIN_DIR/aerospace_menu.sh reload"

sketchybar --add item aerospace.quit popup.aerospace \
           --set aerospace.quit icon="⏻" \
                               label="Quit Aerospace" \
                               click_script="$PLUGIN_DIR/aerospace_menu.sh quit"

sketchybar --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
