#!/bin/zsh
# General Aliases
alias szsh="source ${XDG_CONFIG_HOME}/zsh/.zshrc"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
# alias rm="rm -ri"
# alias mv="mv -i"
alias nv="nvim"
# alias	ls="ls -lah --color=auto --group-directories-first"
# alias df='df -h'
# alias free='free -m'
# alias kchrome="ps -e | rg chrom | awk '{print $1}' | xargs kill -9"
#

alias aider="aider --config ~/.config/.aider.conf.yml --env-file ~/.config/.env-aider"

# default git to git status if there's no args (overrides ohmyzsh g=git alias)
function g() {
  if [[ -z "${*//[[:space:]]/}" ]]; then
    git status
  else
    git "$@"
  fi
}

# Tmux
alias tkill="tmux kill-session -t"
alias tlist="tmux list-sessions"
alias tattach="tmux attach"
alias ta="tattach"
alias tmz="tmux source-file ~/.config/zsh/.zshrc \; respawn-pane -k -t 0 \; respawn-pane -k -t 1" # source zshrc for all visible panes

# eza/ls
alias ls="eza -ax  --icons"
alias ll="eza -albh --icons --git"
alias lr="eza -TL 3 --icons"

# yazi
function y() {
  if command -v yazi &>/dev/null; then
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  else
    return 1
  fi
}

# chezmoi
alias cheza="chezmoi apply"
alias chezd="chezmoi diff"
alias chezl="chezmoi re-add ~/.config/nvim/lazy-lock.json ~/.config/nvim/lazyvim.json"
