#!/bin/zsh
# General Aliases
alias szsh="source ${XDG_CONFIG_HOME}/zsh/.zshrc"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
# alias rm="rm -ri"
# alias mv="mv -i"
alias nv="nvim"
# alias	ls="ls -lah --color=auto --group-directories-first"
# alias df='df -h'
# alias free='free -m'
# alias kchrome="ps -e | rg chrom | awk '{print $1}' | xargs kill -9"

# Git Aliases
alias gs="git status"
alias gc="git commit -S"
alias gce="git commit -S --amend"
alias gcm="git commit -S -m"
alias gca="git commit -S -a"
alias gcam="git commit -S -am"
alias gcem="git commit -S --amend -m"
alias gcee="git commit -S -a --amend --no-edit"
alias ga="git add"
alias gaa="git add -A"
alias gap="git add -p"
alias gpull="git pull"
alias gd="git diff"
alias gdc="git diff --cached"
alias gl="git log"
alias greup="git fetch origin main:main && git rebase main"
alias gst="git stash"
alias gch="git checkout"
# default git to git status if there's no args
function g() {
  if [[ -z "${*//[[:space:]]/}" ]]; then
    git status
  else
    git "$@"
  fi
}

# Tmux
alias tkill="tmux kill-session -t"
alias tlist="tmux list-sessions"
alias tattach="tmux attach"
alias ta="tattach"

# eza/ls
alias ls="eza -ax  --icons"
alias ll="eza -albh --icons --git"
alias lr="eza -TL 3 --icons"

# yazi
function y() {
  if command -v yazi &>/dev/null; then
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  else
    return 1
  fi
}
